spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: everythinginparking3@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  # redis
  data:
    redis:
      host: localhost
      port: 6379

# file
file:
  dir: src/test/resources/static/images/

# authcode
authcode:
  expired-time: 300


# key
kakao:
  key: test
seoul-public-parking-key: test
pusan-public-parking-key: test
