spring:
  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    open-in-view: false

  # DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
